-- Dummy data for public.research_reports
-- Note: session_id is set to NULL to avoid foreign key violations if the parent session doesn't exist.
-- If you have valid session_ids, replace NULL with 'your-uuid-here'.

INSERT INTO public.research_reports (
    user_email,
    company_name,
    nse_symbol,
    company_background,
    business_model,
    management_analysis,
    industry_overview,
    industry_risks,
    profit_loss_statement,
    status,
    tokens_used,
    generation_time_seconds,
    target_price,
    recommendation_rationale,
    recommendation,
    industry_tailwinds,
    demand_drivers,
    summary_table,
    chart_custom,
    price_chart,
    financial_table,
    market_positioning,
    financial_performance,
    growth_outlook,
    valuation_recommendation,
    key_risks,
    company_insider,
    cs_company_insider,
    cs_financial_performance,
    cs_grow_outlook,
    cs_key_risks,
    cs_marketing_positioning,
    cs_value_and_recommendation,
    company_background_h,
    business_model_h,
    management_analysis_h,
    industry_overview_h,
    industry_tailwinds_h,
    demand_drivers_h,
    industry_risks_h,
    is_published,
    published_at
) VALUES 
(
    'test_user@example.com',
    'Reliance Industries Ltd.',
    'RELIANCE',
    'Reliance Industries Limited is an Indian multinational conglomerate headquartered in Mumbai. It has diverse businesses including energy, petrochemicals, natural gas, retail, telecommunications, mass media, and textiles.',
    'Reliance operates through a vertically integrated business model. value chain integration from oil exploration to petrochemicals. Jio Platforms provides digital services, while Reliance Retail operates physical and online stores.',
    'Strong leadership under Mukesh Ambani. The management has successfully pivoted from traditional energy to consumer-facing businesses (Jio, Retail).',
    'The Indian telecommunications and retail sectors are consolidating. Energy transition towards green hydrogen is a key focus.',
    'Regulatory risks in telecom. Volatility in crude oil prices affecting O2C business.',
    'Revenue: ₹900,000 Cr, EBITDA: ₹150,000 Cr, PAT: ₹70,000 Cr (Estimated)',
    'completed',
    1500,
    120,
    3200.00,
    'Strong growth in consumer businesses and stable cash flows from O2C vertical justify a premium valuation.',
    'BUY',
    'Rapid digitization in India; Government push for green energy; Rising middle-class consumption.',
    'Increasing data consumption per user; Shift towards organized retail.',
    'https://placehold.co/600x400/png?text=Summary+Table',
    'https://placehold.co/600x400/png?text=Custom+Chart',
    'https://placehold.co/600x400/png?text=Price+Chart',
    'https://placehold.co/600x400/png?text=Financial+Table',
    'Market leader in Telecom (Jio) and Organized Retail.',
    'Consistent revenue growth of 15% CAGR over last 5 years.',
    'Jio 5G rollout and retail expansion to drive double-digit growth.',
    'Trading at 25x P/E, which is reasonable given the growth profile.',
    'Competition in retail from e-commerce giants; Debt levels.',
    'Promoters hold ~50% stake. No significant insider selling.',
    'Promoter holding remains stable at 50.3%.',
    'Revenue up 15% YoY. Margins stable.',
    '5G monetization to drive ARPU growth.',
    'Oil price volatility remains a key risk.',
    'Dominant player in digital and retail ecosystems.',
    'Buy rating with target of 3200.',
    'About Reliance',
    'Our Business Model',
    'Leadership Analysis',
    'Industry Outlook',
    'Tailwind Factors',
    'Demand Drivers',
    'Risk Factors',
    true,
    NOW()
),
(
    'analyst@firm.com',
    'Tata Consultancy Services',
    'TCS',
    'TCS is an Indian multinational information technology services and consulting company headquartered in Mumbai. It is a part of the Tata Group and operates in 150 locations across 46 countries.',
    'TCS operates on a global delivery model, providing IT services, consulting, and business solutions. It focuses on long-term contracts with large enterprise clients.',
    'Experienced management team with a track record of best-in-class margins. Leadership transition has been smooth.',
    'Global IT spending is expected to grow, driven by cloud migration and AI adoption.',
    'Currency fluctuations (USD/INR). Slowdown in US/Europe economies.',
    'Revenue: ₹200,000 Cr, EBITDA: ₹50,000 Cr, PAT: ₹40,000 Cr',
    'draft',
    1200,
    90,
    4500.00,
    'Market leader in IT services with industry-leading margins and return ratios.',
    'HOLD',
    'Generative AI adoption by enterprises; Cloud transformation deals.',
    'Need for digital transformation and cost optimization by global clients.',
    'https://placehold.co/600x400/png?text=Summary+Table',
    'https://placehold.co/600x400/png?text=Custom+Chart',
    'https://placehold.co/600x400/png?text=Price+Chart',
    'https://placehold.co/600x400/png?text=Financial+Table',
    'Leading global IT services brand with strong client retention.',
    'Maintained 25%+ EBIT margins despite wage inflation.',
    'Steady growth expected in mid-teens.',
    'Valuation is rich at 30x P/E, limiting near-term upside.',
    'US recession fears could delay decision making.',
    'Tata Sons holds majority stake. Clean governance track record.',
    'Tata Sons owns ~72%.',
    'Margins resilient at 25%.',
    'Deal pipeline remains strong at $10Bn+.',
    'US macro headwinds.',
    'Preferred partner for large transformational deals.',
    'Neutral stance due to valuations.',
    'About TCS',
    'TCS Business Model',
    'TCS Leadership',
    'Global IT Industry',
    'IT Sector Tailwinds',
    'Tech Demand Drivers',
    'Key Risks',
    false,
    NULL
);
